export type SettingsCategory =
  | 'projectGeneral'
  | 'projectRun'
  | 'projectActions'
  | 'archives'
  | 'appearance'
  | 'generation'
  | 'keyboard'
  | 'environment'
  | 'agentConfiguration'
  | 'terminal'
  | 'sessions'
  | 'version'
